#!/bin/sh

function hook_preconfigure {
	if [ x$INSTALL_ROOT == x ]; then
		case ${TARGET_SYSNAME} in
			nto*) INSTALL_ROOT=${INSTALL_ROOT_nto} ;;
			linux*) INSTALL_ROOT=${INSTALL_ROOT_linux} ;;
			win32*) INSTALL_ROOT=${INSTALL_ROOT_win32} ;;
			win64*) INSTALL_ROOT=${INSTALL_ROOT_win64} ;;
			darwin*) INSTALL_ROOT=${INSTALL_ROOT_darwin} ;;
		esac
	fi
	prefix=${INSTALL_ROOT}/${cpudir}/usr
	configure_opts="${configure_opts} --includedir=${INSTALL_ROOT_HDR}"
	configure_opts="${configure_opts} --prefix=${prefix}"
	configure_opts="${configure_opts} --disable-shared"
}

function hook_premake {
	unset make_CC
}
