#! /bin/sh

# (C) 1998, 2000, 2002, 2003 Free Software Foundation
# Originally by Alexandre Oliva <oliva@dcc.unicamp.br>

# This script is Free Software, and it can be copied, distributed and
# modified as defined in the GNU General Public License.  A copy of
# its license can be downloaded from http://www.gnu.org/copyleft/gpl.html


if test -f site.exp; then
    echo site.exp already exists >&2
    #exit 1
    rm site.exp
fi

while true; do
  case "$1" in
  --with-testsuite=*) testsuite=`echo "$1" | sed 's/[^=]*=//'`; shift;;
  --srcdir=*) srcdir=`echo "$1" | sed 's/[^=]*=//'`; shift;;

  --prefix=*) prefix=`echo "$1" | sed 's/[^=]*=//'`; shift;;
  --with-gdb=*) GDB_UNDER_TEST=`echo "$1" | sed 's/[^=]*=//'`; shift;;

  --tmpdir=*) tmpdir=`echo "$1" | sed 's/[^=]*=//'`; shift;;

  --help) cat <<\EOF
Runs the testsuite for an installed version of gcc/g++/g77/objc
Copyright (C) 1998  Free Software Foundation
by Alexandre Oliva <oliva@dcc.unicamp.br>

Supported arguments:

--help                        prints this page

--with-testsuite=/some/dir/gcc/testsuite   specify the testsuite directory
--srcdir=/some/dir            same as --with-testsuite=/some/dir/gcc/testsuite
                              [deduced from shell-script pathname]

--prefix=/some/dir            use gcc, g++ and g77 from /some/dir/bin [PATH]
--with-gdb=/some/dir/bin/gdb  use specified gcc program [gcc]
--tmpdir=/some/dir            create temporaries and leave failed programs
                              at specified directory [.]

--   end of argument list; following arguments are passed to runtest
EOF
    exit
  ;;
  
  --) shift; break;;
  *) break;;
  esac
done
  
if test x"${testsuite+set}" != x"set" && test x"${srcdir+set}" != x"set"; then
  file=$0
  while [ -h $file ]; do
    file=`ls -l $file | sed s/'.* -> '//`
  done
  srcdir=`CDPATH=. && cd \`echo "$file" | sed 's,/*[^/]*$,,;s,^$,.,'\`/.. >/dev/null && ${PWDCMD-pwd}`
fi

cat >site.exp <<EOF
set rootme "."
set tmpdir "${tmpdir-`${PWDCMD-pwd}`}"
set srcdir "${testsuite-${srcdir}/gdb/testsuite}"
set CFLAGS ""
set CXXFLAGS ""
set EXECUTABLE ntox86-gdb-6.7
set GDB "${GDB_UNDER_TEST-${prefix}${prefix+/bin/}$GDB_UNDER_TEST}"
lappend boards_dir "../gdb/testsuite/qnxboardfiles"
EOF

#make all the test directories for tmp files
mkdir gdb.arch gdb.asm gdb.base gdb.cp gdb.disasm gdb.dwarf2 gdb.gdb gdb.mi gdb.qnx gdb.server gdb.stabs \
gdb.threads gdb.trace gdb.xml gdb.fortran gdb.hp gdb.java gdb.objc

test x"${GDB_UNDER_TEST}" = x"no" || runtest --tool gdb ${1+"$@"}

exit 0
