/* QNX Neutrino specific low level interface, for the remote server
   for GDB.
   Copyright (C) 2015 Free Software Foundation, Inc.

   This file is part of GDB.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

#include "server.h"
#include "nto-low.h"
#include "regdef.h"
#include "regcache.h"

#include <x86_64/context.h>


/* Definition auto generated from reg-i386.dep.  */
extern void init_registers_amd64 ();
extern struct reg *regs_amd64;
extern const struct target_desc *tdesc_amd64;

//const unsigned char x86_breakpoint[] = { 0xCC };
//#define x86_breakpoint_len 1

/* Returns offset in appropriate Neutrino's context structure.
   Defined in x86/context.h.
   GDBREGNO is index into regs_i386 array.  It is autogenerated and
   hopefully doesn't change.  */
static int
nto_x86_64_register_offset (int gdbregno)
{
  if (gdbregno >= 0 && gdbregno < 22)
    {
      /* GPRs  */
      switch (gdbregno)
	{
	case 0:
	  return offsetof(X86_64_CPU_REGISTERS,rax);
	case 1:
	  return offsetof(X86_64_CPU_REGISTERS,rbx);
	case 2:
	  return offsetof(X86_64_CPU_REGISTERS,rcx);
	case 3:
	  return offsetof(X86_64_CPU_REGISTERS,rdx);
	case 4:
	  return offsetof(X86_64_CPU_REGISTERS,rsi);
	case 5:
	  return offsetof(X86_64_CPU_REGISTERS,rdi);
	case 6:
	  return offsetof(X86_64_CPU_REGISTERS,rbp);
	case 7:
	  return offsetof(X86_64_CPU_REGISTERS,rsp);
	case 8:
	  return offsetof(X86_64_CPU_REGISTERS,r8);
	case 9:
	  return offsetof(X86_64_CPU_REGISTERS,r9);
	case 10:
	  return offsetof(X86_64_CPU_REGISTERS,r10);
	case 11:
	  return offsetof(X86_64_CPU_REGISTERS,r11);
	case 12:
	  return offsetof(X86_64_CPU_REGISTERS,r12);
	case 13:
	  return offsetof(X86_64_CPU_REGISTERS,r13);
	case 14:
	  return offsetof(X86_64_CPU_REGISTERS,r14);
	case 15:
	  return offsetof(X86_64_CPU_REGISTERS,r15);
	case 16:
	  return offsetof(X86_64_CPU_REGISTERS,rip);
	case 17:
	  return offsetof(X86_64_CPU_REGISTERS,rflags);
	case 18:
	case 19:
	case 20:
	case 21:
	case 22:
	case 23:
	default:
	  return -1;
	}
    }
  return -1;
}

static void
nto_x86_64_arch_setup (void)
{
  init_registers_amd64 ();
  the_low_target.num_regs = 22;
  nto_tdesc = tdesc_amd64;
}

struct nto_target_ops the_low_target =
{
  nto_x86_64_arch_setup,
  0, /* num_regs */
  nto_x86_64_register_offset,
  0,// x86_breakpoint,
  0 //x86_breakpoint_len
};



