LIST=OS CPU VARIANT
MAKEFILE=GNUmakefile

$(shell echo "This is an empty file for Do Not Make in here." > nto-x86-o-ntomips/Makefile.dnm)
$(shell echo "This is an empty file for Do Not Make in here." > win32-x86-o-ntomips/Makefile.dnm)
$(shell echo "This is an empty file for Do Not Make in here." > linux-x86-o-ntomips/Makefile.dnm)

include recurse.mk
